apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
namespace: kubeflow
resources:
  - ../../base
  - namespace.yaml
images:
  - name: ghcr.io/kubeflow/training/training-operator
    newTag: v1-f654b1e
secretGenerator:
  - name: training-operator-webhook-cert
    options:
      disableNameSuffixHash: true
